export default function convertNoteToDrumName(note: number) {
    switch (note) {
        // case 'C2': return 'kick';
        // case 'Db2': return 'sidekick';
        // case 'D2': return 'snare';
        // case 'Eb2': return 'handclap';
        // case 'E2': return 'electric_snare';
        // case 'F2': return 'lowtom';
        // case 'Gb2': return 'hihat';
        // case 'G2': return 'hightom';
        // case 'Ab2': return 'pedalhihat';
        // case 'A2': return 'lowtom';
        // case 'Bb2': return 'openhihat';
        // case 'B2': return 'lowmidtom';
        // case 'C3': return 'himidtom';
        // case 'Db3': return 'crash';
        // case 'D3': return 'highmidtom';
        // case 'Eb3': return 'ride';
        case 35: return 'acoustic_bass_drum';
        case 36: return 'bass_drum_1';
        case 37: return 'side_stick';
        case 38: return 'acoustic_snare';
        case 39: return 'hand_clap';
        case 40: return 'electric_snare';
        case 41: return 'low_floor_tom';
        case 42: return 'closed_hi_hat';
        case 43: return 'high_floor_tom';
        case 44: return 'pedal_hi_hat';
        case 45: return 'low_tom';
        case 46: return 'open_hi_hat';
        case 47: return 'low_mid_tom';
        case 48: return 'hi_mid_tom';
        case 49: return 'crash_cymbal_1';
        case 50: return 'high_mid_tom';
        case 51: return 'crash_cymbal_2';
        case 52: return 'ride_cymbal_1';
        case 53: return 'high_tom';
        case 54: return 'ride_cymbal_2';
        case 55: return 'tambourine';
        case 56: return 'splash_cymbal';
        case 57: return 'cowbell';
        case 58: return 'crash_cymbal_3';
        case 59: return 'ride_cymbal_3';
        case 60: return 'high_bongo';
        case 61: return 'low_bongo';
        case 62: return 'mute_high_conga';
        case 63: return 'open_high_conga';
        case 64: return 'low_conga';
        case 65: return 'high_timbale';
        case 66: return 'low_timbale';
        case 67: return 'high_agogo';
        case 68: return 'low_agogo';
        case 69: return 'cabasa';
        case 70: return 'maracas';
        case 71: return 'short_whistle';
        case 72: return 'long_whistle';
        case 73: return 'short_guiro';
        case 74: return 'long_guiro';
        case 75: return 'claves';
        case 76: return 'high_wood_block';
        case 77: return 'low_wood_block';
        case 78: return 'mute_cuica';
        case 79: return 'open_cuica';
        case 80: return 'mute_triangle';
        case 81: return 'open_triangle';
        default: return 'acoustic_bass_drum';
    }
}